import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";

const Home: NextPage = (props) => {
  //const hello = trpc.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Paste bin</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <main className="container mx-auto flex flex-col items-center justify-center p-4">
        Paste bin clone
      </main>      
    </>
  );
};

export default Home;

